# Generated by Django 2.0.6 on 2018-06-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=2000, unique=True)),
                ('title', models.CharField(blank=True, max_length=2000)),
                ('selection', models.CharField(blank=True, max_length=2000)),
                ('folder', models.CharField(max_length=30)),
            ],
        ),
    ]
