# Generated by Django 2.0.6 on 2018-06-22 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=2000, unique=True)),
                ('title', models.CharField(blank=True, max_length=2000)),
                ('selection', models.CharField(blank=True, max_length=2000)),
                ('folder', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='links', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
